name: First workflow

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    name: Clean up
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Print some variables
        run: |
          echo "Github ref: ${{github.ref}}"
          echo "Github event ref: ${{github.event.ref}}"
      - name: Delete branch
        run: |
          git push origin --delete ${{github.ref}}-deploy || true 

           
          