name: First workflow

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  cleanup:
    name: Clean up
    runs-on: ubuntu-latest
    if: github.event.ref == 'branch'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Print some variables
        run: |
          echo "github.ref: ${{github.ref}}"
          echo "github.action: ${{github.action}}"
          echo "github.action_ref: ${{github.action_ref}}"
          echo "github.event: ${{github.event}}"
          echo "github.head_ref: ${{github.head_ref}}"
          echo "github.ref_name: ${{github.ref_name}}"
          echo "github.event: ${{github.event.ref}}"
      - name: Delete branch
        run: |
          git push origin --delete ${{github.ref}}-deploy || true 

           
          